### ISSUE TITLE
GitOps Zero-Conf|Trust|Touch XIoT (SONiC and connected device) management

### ISSUE THREAD

**Issue by mmaymann** [Azure/SONiC#1362]
I suggest we extend SONiC with KubernetesNative device management, to leverage the power of K8s and its ecosystem:
Backend: https://github.com/kcp-dev/kcp
SONiC: https://github.com/k3d-io/k3d

Functionality is similar to (what I interpret as) the thoughts behind [Hedgehog](https://githedgehog.com), 100% free OSS, focusing on existing K8s projects and on Zero-Conf|Trust|Touch XIoT management - using Git(Ops) as single source of truth of desired state.

Disclaimer: I have already suggested this in the [K8s project](https://github.com/kubernetes/kubernetes/issues/118609), but it was closed and I was asked to request this feature here.

Desired state of SONiC devices are stored in Git and managed by Kcp as K3d nodes, pods and validating admission policies:
- [X] GitOps managed Kcp
- [ ] SONiC devices = Kcp workloads = K3d (gateway+spine=dual MLAG? cluster) nodes
- [ ] SONiC apps = K3d pods: K8s deprecated Docker from v1.20: Docker -> [Containerd migration+support](https://github.com/containerd/containerd)
- [ ] SONiC ports = [K3d ValAdmPolicy](https://kubernetes.io/docs/reference/access-authn-authz/validating-admission-policy) / [CiliumHostFirewall](https://isovalent.com/labs/cilium-host-firewall): Attestation, Isolation, Provisioning, Guest, BYOD, XIoT1, XIoT2, ...:
- [ ] - ZeroConf XIoT Onboarding ([Spire](https://github.com/spiffe/spire/issues/4289)):
-- FDO Rendezvous -> ITAM -> XIoT categorization: Unknown, XIoT1, XIoT2, ...
-- CaptivePortal -> Guest/[MDM](https://github.com/spiffe/spire/issues/4306)/BYOD management
- [ ] - ZeroTrust XIoT Attestation ([Spire](https://github.com/spiffe/spire/issues/4281)):
-- 802.1x EAP(oL)-TLS X.509 certificate check
--- TPM_Certify_Info(2) (PCR status): Firmware vers., BootLoader, OS vers., firewall enabled, antivirus enabled, ...
--- Spire-TPM-plugin and missing Keylime functionality
--- MUD -> ITAM -> XIoT identification
--- SBOM -> ITAM -> continuous lightweight vulnerability scanning -> proactive remediation actions
-- (P)NAC/ACL: SpireServer -> SONiC NAC
- [ ] - ZeroTouch XIoT Provisioning:
-- [AWS IoT Greengrass](https://github.com/aws-greengrass)
-- [Tinkerbell](https://github.com/tinkerbell/proposals/issues/67):
--- [RackN DigitalRebar functionality](https://github.com/tinkerbell/proposals/issues/66)
--- [RedFish functionality](https://github.com/tinkerbell/proposals/issues/68)

Monsoon opportunities after migrating SONiC to K3d:
- [ ] Migrate to [Etcd](https://github.com/STORDIS/monsoon/issues/49)
- [ ] Security enhancement using outbound connections with defacto-standard [OTel agent](https://github.com/STORDIS/monsoon/issues/46)
- [ ] Non-invasive kernel-level observability instrumentation and kernel-level runtime security enforcement with [eBPF](https://github.com/STORDIS/monsoon/issues/45)
