### ISSUE TITLE
PINS HLD Tracking

### ISSUE THREAD

**Issue by bocon13** [Azure/SONiC#841]
HLDs
- [ ] PINS Main HLD - #809 (ready for review)
- [ ] P4RT App HLD - #826 (ready for review)
- [ ] P4 Orchagent HLD - #825 (ready for review)
- [ ] P4 APPL DB Schema HLD - #840 (ready for review)
- [ ] SAI P4 Program HLD - (coming soon)
- [ ] P4 Extensions HLD - (coming soon)
- [ ] APPL State DB and Response Path - (coming soon)
- [ ] P4RT Packet IO - (coming soon)

**Comment by smolkaj** [comment]
@bocon13 SAI P4 Program HLD: https://github.com/Azure/SONiC/pull/852

**Comment by mint570** [comment]
Some suggestion on code contributions (just suggestion, no strong opinion):

swss-common:
- We might want to remove component state helper
- All the #define can go into a single pr
- Bazel support and ConsumerNotifier can go into the same pr as the interfaces pr

swss:
- cfgmgr change can go into the response publisher pr
- request parser change can go into the vrf response path pr
- ports orch change can go into the p4orch pr

**Comment by StephenWangGoogle** [comment]
We should move hash orch related item out of MVP

**Comment by bocon13** [comment]
> * We might want to remove component state helper

Only needed for critical state. Then in users (p4rt and swss) of the class, just throw an exception and exit for now

**Comment by zhangyanzhao** [comment]
@bocon13 would you please update the HLD status since the community review is completed. Also please help to add the code PR info, so that community can review.
Thanks.

**Comment by smolkaj** [comment]
Are we planning to merge the HLDs?
